# Generated by Django 5.0 on 2023-12-16 21:26

import gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_gallery_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to=gallery.models.gallery_cover_photo_path),
        ),
    ]
