# Generated by Django 5.0 on 2023-12-16 21:34

import gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_gallery_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(upload_to=gallery.models.user_gallery_path),
        ),
    ]
