# Generated by Django 5.0 on 2023-12-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_comment_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='views',
            field=models.IntegerField(null=True),
        ),
    ]
