# Generated by Django 5.0 on 2023-12-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_alter_gallery_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='views',
            field=models.IntegerField(null=True),
        ),
    ]
