# Generated by Django 5.0 on 2023-12-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_alter_gallery_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
